---
- name: download Geocity
  get_url: dest=/usr/local/share/nmap/nselib/data url='http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz'
- name: uncompressing
  shell: dest=/usr/local/share/nmap/nselib/data gunzip /usr/local/share/nmap/nselib/data/GeoLiteCity.dat.gz

