---
- name: download Geocity
  get_url: dest=/usr/local/share/nmap/nselib/data url='http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz' force=yes
- name: uncompressing
  shell: dest=/usr/local/share/nmap/nselib/data gunzip -f /usr/local/share/nmap/nselib/data/GeoLiteCity.dat.gz 

